version: "3"

tasks:
  migrate-auth:
    deps: [docker-auth]
    desc: "migrations for auth service"
    cmds:
      - go run cmd/migrations-sso/main.go
  migrate-chat:
    deps: [docker-chat]
    desc: "migrations for chat service"
    cmds:
      - go run cmd/migrations-chat/main.go -host=localhost -user=user_chat -password=password_chat -dbname=postgres_chat -port=5600 -sslmode=disable

  docker-chat:
    desc: "docker compose up for chat service (detached mode)"
    cmds:
      - docker compose -f docker-compose.chat.yml -d up postgres
  docker-auth:
    desc: "docker compose up for auth service (detached mode)"
    cmds:
      - docker compose -f docker-compose.sso.yml up -d postgres redis redis-commander

  run-auth:
    deps: [migrate-auth]
    desc: "run auth service"
    cmds:
      - go run cmd/sso/main.go
  run-chat:
    deps: [migrate-chat]
    desc: "run chat service"
    cmds:
      - go run cmd/chat/main.go

  test:
    desc: "test app"
    cmds:
      - go test -v -count=1 ./tests/...
  test-chat:
    desc: "test chat service"
    cmds:
      - go test -v -count=1 ./tests/chat
  test-auth:
    desc: "test auth service"
    cmds:
      - go test -v -count=1 ./tests/auth
