version: "3"

tasks:
  migrate:
    desc: "automigrating postgres db"
    cmds:
      - go run cmd/migrations/main.go -host=localhost -user=user -password=password -dbname=postgres -port=5555 -sslmode=disable

  migrate-test:
    desc: "automigrating postgres testdb"
    cmds:
      - go run cmd/migrations/main.go -host=localhost -user=user_test -password=password_test -dbname=postgres_test -port=5556 -sslmode=disable
  docker-prod:
    desc: "docker compose up for production env"
    cmds:
      - docker compose up postgres redis redis-commander
  docker-local:
    desc: "docker compose up for local env"
    cmds:
      - docker compose up postgres_test redis redis-commander
  test:
    desc: "test app"
    cmds:
      - go test -v -count=1 ./tests/...
  test-chat:
    desc: "test chat service"
    cmds:
      - go test -v -count=1 ./tests/chat
  test-auth:
    desc: "test chat service"
    cmds:
      - go test -v -count=1 ./tests/auth
