version: "3"

tasks:
  migrate-sso:
    desc: "automigrating postgres db for sso service"
    cmds:
      - go run cmd/migrations-sso/main.go -host=localhost -user=user -password=password -dbname=postgres -port=5555 -sslmode=disable
  migrate-sso-test:
    desc: "automigrating postgres testdb for sso service"
    cmds:
      - go run cmd/migrations-sso/main.go -host=localhost -user=user_test -password=password_test -dbname=postgres_test -port=5556 -sslmode=disable
  migrate-chat:
    desc: "automigrating postgres db for chat service"
    cmds:
      - go run cmd/migrations-chat/main.go -host=localhost -user=user_chat -password=password_chat -dbname=postgres_chat -port=5600 -sslmode=disable
  migrate-chat-test:
    desc: "automigrating postgres testdb for chat service"
    cmds:
      - go run cmd/migrations-chat/main.go -host=localhost -user=user_chat_test -password=password_chat_test -dbname=postgres_chat_test -port=5601 -sslmode=disable
  docker-chat-prod:
    desc: "docker compose up for production chat service"
    cmds:
      - docker compose -f docker-compose.chat.yml up postgres_chat
  docker-chat-local:
    desc: "docker compose up for local chat service"
    cmds:
      - docker compose -f docker-compose.chat.yml up postgres_chat_test
  docker-sso-prod:
    desc: "docker compose up for production sso service"
    cmds:
      - docker compose -f docker-compose.sso.yml up postgres redis redis-commander
  docker-sso-local:
    desc: "docker compose up for local sso service"
    cmds:
      - docker compose -f docker-compose.sso.yml up postgres_test redis redis-commander
  test:
    desc: "test app"
    cmds:
      - go test -v -count=1 ./tests/...
  test-chat:
    desc: "test chat service"
    cmds:
      - go test -v -count=1 ./tests/chat
  test-auth:
    desc: "test chat service"
    cmds:
      - go test -v -count=1 ./tests/auth
