version: "3"

tasks:
  # для миграций
  migrate-auth:
    desc: "migrations for auth service"
    cmds:
      - go run cmd/migrations-sso/main.go
  migrate-chat:
    desc: "migrations for chat service"
    cmds:
      - go run cmd/migrations-chat/main.go

  # для запуска сервиса локально
  docker-chat:
    desc: "docker compose up for chat service (detached mode)"
    cmds:
      - docker compose -f docker-compose.chat.yml up -d --remove-orphans postgres adminer
  docker-auth:
    desc: "docker compose up for auth service (detached mode)"
    cmds:
      - docker compose -f docker-compose.sso.yml up -d --remove-orphans postgres redis redis-commander adminer

  # для запуска сервиса в контейнере
  in-docker-auth:
    desc: "docker compose up for up sso service in docker "
    cmds:
      - docker compose -f docker-compose.sso.yml up -d --remove-orphans sso
  in-docker-chat:
    desc: "docker compose up for up chat service in docker "
    cmds:
      - docker compose -f docker-compose.chat.yml up -d --remove-orphans chat

  # для запуска сервиса локально
  run-auth:
    deps: [migrate-auth]
    desc: "run auth service"
    cmds:
      - go run cmd/sso/main.go
  run-chat:
    deps: [migrate-chat]
    desc: "run chat service"
    cmds:
      - go run cmd/chat/main.go

  # тесты
  test:
    desc: "test app"
    cmds:
      - go test -v -count=1 ./tests/...
  test-chat:
    desc: "test chat service"
    cmds:
      - go test -v -count=1 ./tests/chat
  test-auth:
    desc: "test auth service"
    cmds:
      - go test -v -count=1 ./tests/auth
