// Code generated by MockGen. DO NOT EDIT.
// Source: constructor.go

// Package mock_authusecases is a generated GoMock package.
package mock_authusecases

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Krokozabra213/sso/internal/auth/domain"
	jwtv1 "github.com/Krokozabra213/sso/pkg/jwt-manager/v1"
	gomock "github.com/golang/mock/gomock"
)

// MockIJWTManager is a mock of IJWTManager interface.
type MockIJWTManager struct {
	ctrl     *gomock.Controller
	recorder *MockIJWTManagerMockRecorder
}

// MockIJWTManagerMockRecorder is the mock recorder for MockIJWTManager.
type MockIJWTManagerMockRecorder struct {
	mock *MockIJWTManager
}

// NewMockIJWTManager creates a new mock instance.
func NewMockIJWTManager(ctrl *gomock.Controller) *MockIJWTManager {
	mock := &MockIJWTManager{ctrl: ctrl}
	mock.recorder = &MockIJWTManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIJWTManager) EXPECT() *MockIJWTManagerMockRecorder {
	return m.recorder
}

// GenerateTokens mocks base method.
func (m *MockIJWTManager) GenerateTokens(data *jwtv1.Data) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokens", data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateTokens indicates an expected call of GenerateTokens.
func (mr *MockIJWTManagerMockRecorder) GenerateTokens(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokens", reflect.TypeOf((*MockIJWTManager)(nil).GenerateTokens), data)
}

// ParseAccess mocks base method.
func (m *MockIJWTManager) ParseAccess(token string) (*jwtv1.AccessData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAccess", token)
	ret0, _ := ret[0].(*jwtv1.AccessData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAccess indicates an expected call of ParseAccess.
func (mr *MockIJWTManagerMockRecorder) ParseAccess(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAccess", reflect.TypeOf((*MockIJWTManager)(nil).ParseAccess), token)
}

// ParseRefresh mocks base method.
func (m *MockIJWTManager) ParseRefresh(token string) (*jwtv1.RefreshData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseRefresh", token)
	ret0, _ := ret[0].(*jwtv1.RefreshData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseRefresh indicates an expected call of ParseRefresh.
func (mr *MockIJWTManagerMockRecorder) ParseRefresh(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseRefresh", reflect.TypeOf((*MockIJWTManager)(nil).ParseRefresh), token)
}

// MockIHasher is a mock of IHasher interface.
type MockIHasher struct {
	ctrl     *gomock.Controller
	recorder *MockIHasherMockRecorder
}

// MockIHasherMockRecorder is the mock recorder for MockIHasher.
type MockIHasherMockRecorder struct {
	mock *MockIHasher
}

// NewMockIHasher creates a new mock instance.
func NewMockIHasher(ctrl *gomock.Controller) *MockIHasher {
	mock := &MockIHasher{ctrl: ctrl}
	mock.recorder = &MockIHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHasher) EXPECT() *MockIHasherMockRecorder {
	return m.recorder
}

// HashJWTTokenHMAC mocks base method.
func (m *MockIHasher) HashJWTTokenHMAC(token string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashJWTTokenHMAC", token)
	ret0, _ := ret[0].(string)
	return ret0
}

// HashJWTTokenHMAC indicates an expected call of HashJWTTokenHMAC.
func (mr *MockIHasherMockRecorder) HashJWTTokenHMAC(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashJWTTokenHMAC", reflect.TypeOf((*MockIHasher)(nil).HashJWTTokenHMAC), token)
}

// MockITokenProvider is a mock of ITokenProvider interface.
type MockITokenProvider struct {
	ctrl     *gomock.Controller
	recorder *MockITokenProviderMockRecorder
}

// MockITokenProviderMockRecorder is the mock recorder for MockITokenProvider.
type MockITokenProviderMockRecorder struct {
	mock *MockITokenProvider
}

// NewMockITokenProvider creates a new mock instance.
func NewMockITokenProvider(ctrl *gomock.Controller) *MockITokenProvider {
	mock := &MockITokenProvider{ctrl: ctrl}
	mock.recorder = &MockITokenProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenProvider) EXPECT() *MockITokenProviderMockRecorder {
	return m.recorder
}

// CheckToken mocks base method.
func (m *MockITokenProvider) CheckToken(ctx context.Context, token string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckToken", ctx, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckToken indicates an expected call of CheckToken.
func (mr *MockITokenProviderMockRecorder) CheckToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckToken", reflect.TypeOf((*MockITokenProvider)(nil).CheckToken), ctx, token)
}

// SaveToken mocks base method.
func (m *MockITokenProvider) SaveToken(ctx context.Context, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToken", ctx, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveToken indicates an expected call of SaveToken.
func (mr *MockITokenProviderMockRecorder) SaveToken(ctx, token, expiresAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToken", reflect.TypeOf((*MockITokenProvider)(nil).SaveToken), ctx, token, expiresAt)
}

// MockIUserProvider is a mock of IUserProvider interface.
type MockIUserProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIUserProviderMockRecorder
}

// MockIUserProviderMockRecorder is the mock recorder for MockIUserProvider.
type MockIUserProviderMockRecorder struct {
	mock *MockIUserProvider
}

// NewMockIUserProvider creates a new mock instance.
func NewMockIUserProvider(ctrl *gomock.Controller) *MockIUserProvider {
	mock := &MockIUserProvider{ctrl: ctrl}
	mock.recorder = &MockIUserProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserProvider) EXPECT() *MockIUserProviderMockRecorder {
	return m.recorder
}

// IsAdmin mocks base method.
func (m *MockIUserProvider) IsAdmin(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdmin", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAdmin indicates an expected call of IsAdmin.
func (mr *MockIUserProviderMockRecorder) IsAdmin(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdmin", reflect.TypeOf((*MockIUserProvider)(nil).IsAdmin), ctx, userID)
}

// SaveUser mocks base method.
func (m *MockIUserProvider) SaveUser(ctx context.Context, user *domain.User) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", ctx, user)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockIUserProviderMockRecorder) SaveUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockIUserProvider)(nil).SaveUser), ctx, user)
}

// User mocks base method.
func (m *MockIUserProvider) User(ctx context.Context, username string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, username)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockIUserProviderMockRecorder) User(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockIUserProvider)(nil).User), ctx, username)
}

// UserByID mocks base method.
func (m *MockIUserProvider) UserByID(ctx context.Context, userID int64) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByID", ctx, userID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByID indicates an expected call of UserByID.
func (mr *MockIUserProviderMockRecorder) UserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByID", reflect.TypeOf((*MockIUserProvider)(nil).UserByID), ctx, userID)
}

// MockIAppProvider is a mock of IAppProvider interface.
type MockIAppProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIAppProviderMockRecorder
}

// MockIAppProviderMockRecorder is the mock recorder for MockIAppProvider.
type MockIAppProviderMockRecorder struct {
	mock *MockIAppProvider
}

// NewMockIAppProvider creates a new mock instance.
func NewMockIAppProvider(ctrl *gomock.Controller) *MockIAppProvider {
	mock := &MockIAppProvider{ctrl: ctrl}
	mock.recorder = &MockIAppProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAppProvider) EXPECT() *MockIAppProviderMockRecorder {
	return m.recorder
}

// AppByID mocks base method.
func (m *MockIAppProvider) AppByID(ctx context.Context, appID int) (*domain.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppByID", ctx, appID)
	ret0, _ := ret[0].(*domain.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppByID indicates an expected call of AppByID.
func (mr *MockIAppProviderMockRecorder) AppByID(ctx, appID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppByID", reflect.TypeOf((*MockIAppProvider)(nil).AppByID), ctx, appID)
}
